[project]
name = 'test-contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.arcus-vault]
path = 'contracts/arcus-vault.clar'
clarity_version = 2
epoch = 2.1

[contracts.lp-token]
path = 'contracts/lp-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
