[project]
name = 'Contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Sip-10]
path = 'contracts/Sip-10.clar'
clarity_version = 2
epoch = 2.1

[contracts.arcus-swap]
path = 'contracts/arcus-swap.clar'
clarity_version = 2
epoch = 2.1

[contracts.arcus-token]
path = 'contracts/arcus-token.clar'
clarity_version = 2
epoch = 2.1

[contracts.satosh-token]
path = 'contracts/satosh-token.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
